namespace WorkoutTracker.Helpers;

public sealed record ExerciseInfo(string Summary, IReadOnlyList<string> Cues);

public static class ExerciseInfoCatalog
{
    private static readonly Dictionary<string, ExerciseInfo> ExactInfoMap = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Ab Rollout"] = Create("A demanding core drill that teaches you to resist arching as you reach forward, so the win is staying braced instead of rolling out as far as possible.", "Brace hard before you start moving.", "Keep the hips and ribs stacked as you reach forward.", "Only go as far as you can without losing trunk control."),
        ["Arnold Press"] = Create("A rotating dumbbell press that challenges the shoulders through a longer path, so smooth control matters more than rushing the rep.", "Start with the elbows slightly in front of you.", "Rotate smoothly as you press instead of making it one jerky motion.", "Lower under control and reverse the path cleanly."),
        ["Assisted Pull-Up"] = Create("A supported pull-up that helps you practice the full vertical-pull pattern while you build the strength to do more of the work yourself.", "Stay tall through the torso before you pull.", "Think about driving the elbows down instead of just bending the arms.", "Lower with control so every rep still looks strong."),
        ["Back Squat"] = Create("A foundational squat that builds strong legs and a strong torso by teaching you to stay braced from the unrack to the top of every rep.", "Take a breath and brace before you start down.", "Keep your whole foot rooted as the knees track naturally.", "Drive up through the midfoot and stand tall without folding forward."),
        ["Barbell Row"] = Create("A bent-over barbell row that builds lats, rhomboids, and upper-back strength while the torso stays braced.", "Set your hinge and keep the torso angle steady.", "Row the bar toward the lower ribs or upper stomach.", "Lower with control instead of letting the weight drop."),
        ["Barbell Bench Press"] = Create("A classic chest press where a tight setup matters just as much as the press itself, helping you move the bar with more control and consistency.", "Set your upper back and stay tight before you unrack.", "Lower the bar to the same touch point each rep.", "Press up with stacked wrists and steady elbow control."),
        ["Barbell Curl"] = Create("A classic biceps curl where the arms should do the work, not the hips or lower back trying to help the bar swing up.", "Keep the elbows close to your sides.", "Lift without rocking the torso.", "Lower the bar slowly so the biceps stay working."),
        ["Bird Dog"] = Create("A control-focused core drill that teaches you to move the arms and legs without letting the low back or hips wobble around.", "Keep your ribs down and hips level the whole time.", "Reach long through the hand and heel instead of lifting high.", "Move slow enough that your torso stays quiet."),
        ["Bodyweight Squat"] = Create("A simple squat pattern that helps you build leg strength and movement quality by owning every part of the rep without added load.", "Keep your feet planted and chest lifted.", "Sit down with control and let the knees track naturally.", "Push through the floor and stand all the way tall."),
        ["Box Squat"] = Create("A squat-to-box variation that teaches you to control depth and stay tight in the bottom instead of dropping into it.", "Reach back to the box under control.", "Touch the box without fully relaxing into it.", "Drive back up through the feet while staying braced."),
        ["Bulgarian Split Squat"] = Create("A tough single-leg exercise that puts a lot of work into the front leg, especially when you stay balanced and move straight up and down.", "Keep most of your weight over the front foot.", "Lower straight down instead of drifting forward.", "Drive through the front leg to stand back up."),
        ["Cable Crossover"] = Create("A chest isolation movement where the goal is to bring the arms together with the chest doing the work, not to chase extra range by shrugging forward.", "Keep a soft bend in the elbows the whole time.", "Bring the hands together by squeezing through the chest.", "Control the stretch on the way back."),
        ["Cable Chest Fly"] = Create("A cable fly variation that keeps constant chest tension while the arms sweep together in a controlled arc.", "Keep a gentle bend in the elbows throughout.", "Bring the hands together by squeezing through the chest, not by shrugging.", "Return slowly so the stretch stays controlled."),
        ["Cable Curl"] = Create("A biceps curl with steady cable tension, so it rewards smooth reps and punishes trying to cheat with the torso.", "Keep your elbows close to your body.", "Curl smoothly without leaning back.", "Lower under control so the tension stays on the biceps."),
        ["Cable Lateral Raise"] = Create("A shoulder-isolation raise that keeps steady tension on the side delts, so the goal is smooth control rather than throwing the weight around.", "Stand tall and brace before the arm starts moving.", "Lift out in a smooth arc without shrugging the shoulder up.", "Lower slowly so the delt keeps working the whole way down."),
        ["Cable Triceps Pushdown"] = Create("A straightforward triceps builder where clean elbow control matters more than using extra body movement to force the handle down.", "Keep your upper arms pinned near your sides.", "Finish the rep by straightening the elbows, not by leaning over the cable.", "Let the handle come back up under control."),
        ["Cable Woodchopper"] = Create("A diagonal core movement that teaches you to rotate with control through the trunk instead of letting the hips and arms throw the weight around.", "Turn through the ribcage while keeping the hips steady.", "Move the handle on one clean diagonal line.", "Control both the pull and the return."),
        ["Calf Raise"] = Create("A basic calf exercise that works best when you move through the ankle with control instead of bouncing through partial reps.", "Push through the ball of the foot.", "Pause briefly when you reach the top.", "Lower slowly into a comfortable stretch."),
        ["Chest Dip"] = Create("A dip variation that shifts a little more work to the chest, as long as you stay controlled and do not let the shoulders collapse forward.", "Use a slight forward lean as you lower.", "Keep the shoulders packed instead of shrugging up.", "Press back up smoothly through the range you can own."),
        ["Chest Press Machine"] = Create("A stable pressing machine that lets you focus on the chest and triceps without worrying about balancing the load.", "Set the seat so the handles start around chest height.", "Press smoothly while keeping the shoulders down.", "Control the return so the chest stays engaged."),
        ["Chest-Supported Row"] = Create("A supported row that lets you focus on squeezing through the upper back without spending energy trying to hold a bent-over position.", "Stay heavy on the pad so the torso does not start lifting off.", "Pull the elbows back in a smooth path instead of yanking with the hands.", "Pause briefly at the top without shrugging."),
        ["Close-Grip Bench Press"] = Create("A bench press variation that asks the triceps to do more of the work while still keeping the chest involved.", "Keep the elbows a bit more tucked than your normal bench press.", "Lower the bar under control to the lower chest area.", "Press straight up with stacked wrists and steady elbows."),
        ["Concentration Curl"] = Create("A strict one-arm curl that makes it easier to feel the biceps working because the upper arm stays locked in place.", "Keep the upper arm planted and still.", "Curl through a smooth full range.", "Lower slowly instead of letting the weight drop."),
        ["Crunches"] = Create("A short-range ab exercise that should feel like the abs curling the torso up, not the neck pulling the head forward.", "Lift the shoulders by bracing the abs first.", "Keep the neck relaxed and the chin easy.", "Lower back down with control."),
        ["Dead Bug"] = Create("A bracing drill that teaches you to keep the trunk locked in while the arms and legs move, which carries over well to almost every other lift.", "Keep a gentle low-back contact with the floor.", "Exhale as you reach so the ribs stay down.", "Only extend as far as you can without losing control."),
        ["Deadlift"] = Create("A full-body strength lift where a strong setup and tight brace let you push the floor away instead of yanking the bar up with your back.", "Brace hard before the bar leaves the floor.", "Keep the bar close to your body as it rises.", "Stand tall at the top without leaning back."),
        ["Decline Bench Press"] = Create("A decline press that gives you a stable pressing path and a slightly different chest angle, but still rewards a tight setup and controlled touch point.", "Stay locked into the bench before you start pressing.", "Lower with control to the same spot each rep.", "Press smoothly instead of bouncing out of the bottom."),
        ["Diamond Push-Ups"] = Create("A close-hand push-up that really asks the triceps to work, so clean body tension matters more than going fast.", "Keep the hands close and the elbows controlled.", "Only lower as far as you can stay stable.", "Press back up without losing your plank position."),
        ["Dips"] = Create("A bodyweight press that builds chest, shoulders, and triceps when you stay controlled and keep the shoulders in a strong position.", "Keep the shoulders packed as you lower.", "Descend only as far as you can stay stable.", "Press back up smoothly without bouncing through the bottom."),
        ["Dumbbell Bench Press"] = Create("A chest press that gives each arm its own path, which makes control and even movement from side to side especially important.", "Set your shoulder blades before the first rep.", "Lower both dumbbells evenly and under control.", "Press up without letting the elbows flare too wide."),
        ["Dumbbell Curl"] = Create("A straightforward biceps curl where the best reps come from keeping the body quiet and letting the arms do the work.", "Keep the elbows close to your sides.", "Curl without swinging the torso.", "Lower slowly so the biceps stay loaded."),
        ["Dumbbell Floor Press"] = Create("A floor-based press that teaches control and a strong lockout while keeping the shoulder range a little more limited.", "Set the shoulders before you lower the weights.", "Pause lightly when the upper arms meet the floor.", "Press both dumbbells up together with control."),
        ["Dumbbell Fly"] = Create("A chest isolation movement that should feel like a wide controlled stretch and squeeze, not a loose shoulder swing.", "Keep a small bend in the elbows.", "Lower only as far as your shoulders stay comfortable.", "Bring the weights back together by squeezing through the chest."),
        ["Dumbbell Kickback"] = Create("A triceps isolation move that works best when the upper arm stays locked in place and only the elbow moves.", "Set the upper arm first and keep it steady.", "Straighten the elbow fully at the top.", "Do not let the shoulder swing the weight."),
        ["Dumbbell Romanian Deadlift"] = Create("A hinge pattern that teaches you to load the hamstrings and glutes by sending the hips back while the dumbbells stay close to your legs.", "Push your hips back first and let the dumbbells track close.", "Keep a soft knee bend and a long neutral spine.", "Stand tall by driving the hips through, not by yanking with the back."),
        ["Dumbbell Shoulder Press"] = Create("A dumbbell overhead press that builds shoulder strength while asking each arm to stay stable on its own path.", "Start from a solid base with the ribs down.", "Press up without shrugging early.", "Lower both dumbbells with control."),
        ["EZ-Bar Curl"] = Create("A biceps curl with a more wrist-friendly grip that still rewards strict reps over body English.", "Stand tall and keep the elbows close.", "Curl smoothly without leaning back.", "Lower under control instead of dropping the bar."),
        ["Elevated Push-Up"] = Create("A more approachable push-up variation that still teaches the same strong body line and pressing mechanics as the floor version.", "Brace the trunk before each rep.", "Lower the chest with control toward the support.", "Press away without letting the hips sag."),
        ["Face Pull"] = Create("A posture-friendly upper-back exercise that teaches you to pull with the rear shoulders and upper back instead of letting the neck and traps take over.", "Pull toward your face with the elbows leading high.", "Keep the chest lifted while the shoulders stay down.", "Pause briefly when the upper back is fully engaged."),
        ["Face Pulls"] = Create("A posture-friendly upper-back exercise that teaches you to pull with the rear shoulders and upper back instead of letting the neck and traps take over.", "Pull toward your face with the elbows leading high.", "Keep the chest lifted while the shoulders stay down.", "Pause briefly when the upper back is fully engaged."),
        ["Farmer Carry"] = Create("A loaded carry that builds grip and trunk strength by asking you to walk tall while the weights try to pull you out of position.", "Stand tall with the shoulders down.", "Take short controlled steps.", "Do not lean or sway side to side."),
        ["Flutter Kicks"] = Create("A core endurance drill that works best when the abs stay braced and the legs move in small controlled kicks instead of big swings.", "Keep the lower back controlled against the floor.", "Use small steady kicks rather than large ones.", "Stay braced through the whole set."),
        ["Front Raise"] = Create("A front-delt isolation raise where the goal is a smooth lift, not swinging the weight high with the whole body.", "Keep the ribs down and torso still.", "Lift smoothly without using momentum.", "Lower under control."),
        ["Front Squat"] = Create("A front-loaded squat that challenges your quads and upper back at the same time, rewarding a tall torso and strong brace.", "Keep the elbows high so the bar stays secure on the shoulders.", "Sit down under control while staying tall through the chest.", "Drive straight up without letting the torso fold."),
        ["Goblet Squat"] = Create("A front-loaded squat that teaches good posture and bracing while giving you an easy way to sit down and stand up with control.", "Hold the weight close to your chest.", "Sit down between the knees under control.", "Drive through the whole foot to stand tall."),
        ["Hack Squat"] = Create("A machine squat that lets you load the quads hard, as long as you move through the sled with control instead of chasing depth you cannot own.", "Set your feet where you can stay stable.", "Lower smoothly without losing position on the pad.", "Press the sled away through the midfoot."),
        ["Half-Kneeling Shoulder Press"] = Create("A shoulder press that also challenges your balance and trunk control, which makes clean alignment part of the exercise.", "Brace the core and squeeze the glute on the down-knee side.", "Press straight overhead without leaning away.", "Keep the torso stacked from start to finish."),
        ["Hammer Curl"] = Create("A neutral-grip curl that builds the arms well when you keep the thumbs-up position and avoid swinging the dumbbells.", "Keep the palms facing each other the whole rep.", "Curl without rocking the torso.", "Lower slowly so the arms stay loaded."),
        ["Hamstring Curl"] = Create("A direct hamstring exercise where the goal is to feel the back of the legs doing the work instead of kicking or arching to cheat the rep.", "Set yourself firmly into the pad before you start.", "Curl smoothly without jerking the weight.", "Lower slowly so the hamstrings stay loaded."),
        ["Hanging Knee Raise"] = Create("A hanging core move that teaches you to lift the knees with the trunk braced instead of swinging them upward.", "Bring the knees up with the abs, not momentum.", "Stay tall through the shoulders as you hang.", "Lower slowly so the swing stays small."),
        ["Hanging Leg Raise"] = Create("A harder hanging ab exercise that asks you to lift the legs while keeping the torso steady and the swing under control.", "Brace before the legs start moving.", "Do not let the shoulders and torso start swinging around.", "Lower slowly to keep tension on the abs."),
        ["Heel-to-Toe Walk"] = Create("A simple balance drill that improves control by narrowing your base of support and asking you to move carefully.", "Place one foot directly in front of the other.", "Keep your posture tall and eyes forward.", "Move slowly enough to stay balanced."),
        ["Hip Hinge Drill"] = Create("A teaching drill that helps you learn what it feels like to load the hips without rounding or overextending the back.", "Push the hips back first.", "Keep a soft bend in the knees.", "Maintain a long neutral spine throughout."),
        ["Hip Thrust"] = Create("A glute-focused lift where the top position should come from the hips driving through, not from arching the lower back.", "Set the ribs down before the rep starts.", "Drive through the heels and squeeze the glutes at the top.", "Avoid overextending the lower back to finish the rep."),
        ["Incline Bench Press"] = Create("An incline barbell press that shifts more work toward the upper chest and shoulders while still rewarding a tight bench setup.", "Keep the upper back tight against the bench.", "Lower the bar to the upper chest with control.", "Press back up without shrugging the shoulders."),
        ["Incline Dumbbell Curl"] = Create("A curl variation that places the biceps under a bigger stretch, so slow controlled reps usually feel much better than trying to force the weight up.", "Let the arms hang naturally behind the torso.", "Keep the shoulders relaxed as you curl.", "Lower fully with control."),
        ["Incline Dumbbell Press"] = Create("An incline dumbbell press that lets each arm move freely, making smooth control and even pressing from side to side really important.", "Keep the chest lifted and shoulders set.", "Lower the dumbbells evenly on both sides.", "Press up smoothly without bouncing."),
        ["Incline Push-Up"] = Create("A hands-elevated push-up that keeps the same pressing pattern while making it easier to stay strong through the body line.", "Hold a straight line from shoulders to heels.", "Lower the chest toward the support with control.", "Press back up without losing trunk tension."),
        ["Landmine Press"] = Create("A shoulder-friendly press that follows an arc, so it often feels smoother on the shoulders while still training strong overhead pressing mechanics.", "Brace and keep the ribs stacked.", "Press up and slightly forward along the bar path.", "Lower under control back to the shoulder line."),
        ["Lat Pulldown"] = Create("A vertical pull that teaches you to use the lats to bring the elbows down, not just bend the arms and hope the bar moves.", "Set the chest tall before you start the pull.", "Think about driving your elbows down toward your sides.", "Bring the bar to the upper chest without shrugging."),
        ["Lateral Raise"] = Create("A side-delt isolation lift where the best reps are the ones you can control cleanly, not the ones you swing the highest.", "Keep a slight bend in the elbows.", "Raise the arms with control instead of momentum.", "Stop at a height you can own without shrugging."),
        ["Leg Extension"] = Create("A quad isolation exercise that works best when you lift with control and keep tension on the front of the thigh instead of swinging the pad.", "Line the knee up with the machine pivot before the set starts.", "Lift smoothly and squeeze the quads at the top.", "Lower with control instead of letting the weight fall."),
        ["Leg Press"] = Create("A machine leg drive that lets you load the quads and glutes hard while staying supported, as long as you keep the rep smooth and controlled.", "Keep your full foot planted on the platform.", "Lower only as deep as you can stay stable and controlled.", "Press the platform away without snapping the knees into lockout."),
        ["Machine Chest Press"] = Create("A stable chest press that lets you focus on pressing through the chest and triceps without worrying about balancing the load.", "Set the seat so the handles line up around chest height.", "Press smoothly while keeping the shoulders down and back.", "Control the return so the chest stays loaded."),
        ["Machine Incline Press"] = Create("A guided incline press that lets you focus on driving through the upper chest and shoulders without worrying about balancing the load.", "Set the shoulders firmly against the pad.", "Press smoothly without slamming into lockout.", "Control the return all the way back to the start."),
        ["Machine Shoulder Press"] = Create("A machine overhead press that gives you a stable path, so you can focus on pressing well and keeping the shoulders in a strong position.", "Set the seat so the handles start near shoulder height.", "Press smoothly without shrugging early.", "Lower back down with control."),
        ["Neutral-Grip Lat Pulldown"] = Create("A shoulder-friendly pulldown variation that often feels smoother while still teaching you to drive the elbows down with the lats.", "Lift the chest before the pull starts.", "Drive the elbows down and slightly back.", "Bring the handle toward the upper chest under control."),
        ["Overhead Press"] = Create("A strict press that builds shoulders, triceps, and trunk strength by asking you to move the weight overhead without losing body position.", "Brace before the weight leaves shoulder height.", "Press straight up without leaning back hard.", "Finish tall with the ribs stacked under the load."),
        ["Overhead Triceps Extension"] = Create("A triceps move that biases the long head, and it feels best when the upper arms stay quiet and the ribs stay down.", "Keep the upper arms pointed up and steady.", "Lower behind the head only as far as you can control.", "Extend smoothly without flaring the ribs."),
        ["Pallof Press"] = Create("An anti-rotation drill that teaches your core to resist being pulled sideways, so the win is staying still while the arms move.", "Brace before you press the hands away.", "Keep your hips and shoulders square to the front.", "Move straight out and back in without letting the torso twist."),
        ["Pause Back Squat"] = Create("A paused squat that builds discipline in the bottom position by forcing you to stay tight instead of bouncing out of the hole.", "Stay braced during the pause.", "Keep pressure through the whole foot.", "Drive straight up without letting the chest collapse."),
        ["Pec Deck Fly"] = Create("A guided chest fly that makes it easy to focus on a smooth squeeze and stretch without turning it into a shoulder shrug.", "Set the seat so the arms line up comfortably with the chest.", "Bring the arms together smoothly.", "Control the opening phase instead of letting it pull you back."),
        ["Plank"] = Create("A simple but honest core hold where the goal is to own a straight strong line instead of just surviving the clock.", "Make one straight line from shoulders to heels.", "Brace the abs and squeeze the glutes.", "Do not let the lower back sag."),
        ["Plank Knee Drive"] = Create("A moving plank variation that asks you to keep the torso steady while the hip moves, which is where the real challenge is.", "Keep the shoulders stacked over the hands.", "Drive the knee in without collapsing the torso.", "Return to plank slowly and under control."),
        ["Preacher Curl"] = Create("A strict curl that takes momentum away and makes the biceps do the work from start to finish.", "Keep the upper arm planted on the pad.", "Lift smoothly without rocking the shoulders.", "Control the lowering phase all the way down."),
        ["Pull-Up"] = Create("A bodyweight vertical pull that rewards a tight body position and strong elbow drive more than just trying to get the chin over the bar.", "Start from a stable hang with the trunk braced.", "Drive the elbows down as you pull.", "Lower all the way back with control."),
        ["Push Press"] = Create("A powerful overhead press that uses a small leg drive, but still depends on timing and control to send the weight overhead cleanly.", "Use a short controlled dip before you drive up.", "Transfer the leg drive into the press without losing balance.", "Finish tall with the weight overhead."),
        ["Push-Up"] = Create("A foundational bodyweight press where the whole body should move as one piece, not as a loose chest drop with the hips sagging behind.", "Keep the body in one straight line.", "Lower with control and let the elbows track naturally.", "Press away from the floor without losing your plank."),
        ["Rear Delt Cable Fly"] = Create("A rear-delt movement with steady cable tension, which makes smooth control and shoulder position more important than moving a lot of weight.", "Stay tall or braced in the setup.", "Open the arms wide without shrugging.", "Return slowly to the start."),
        ["Rear Delt Fly"] = Create("A rear-shoulder fly that helps build the back side of the shoulders when you open the arms with control instead of heaving the weight.", "Set your hinge or brace before the first rep.", "Sweep the arms out without shrugging.", "Squeeze briefly at the top."),
        ["Rear-Foot Elevated Split Squat"] = Create("A challenging single-leg squat variation that asks the front leg to do most of the work while you stay balanced and controlled.", "Keep most of the load on the front leg.", "Lower under control and keep the torso steady.", "Push through the front foot to stand."),
        ["Resistance Band Row"] = Create("A simple row that teaches you to finish with the upper back by pulling the elbows behind you instead of letting the shoulders roll forward.", "Lift the chest and keep the shoulders down before you pull.", "Drive the elbows back toward your ribs.", "Pause briefly when the hands reach your torso."),
        ["Reverse Curl"] = Create("A pronated-grip curl that shifts more work to the forearms and brachialis, so strict wrist and elbow control matters.", "Keep the wrists firm and elbows close.", "Raise the bar without swinging the torso.", "Lower with control."),
        ["Reverse Lunge"] = Create("A controlled lunge where stepping back usually makes it easier to stay balanced and load the front leg well.", "Step back softly and keep the front foot rooted.", "Lower until both knees bend naturally.", "Drive through the front foot to return to standing."),
        ["Reverse Pec Deck Fly"] = Create("A guided rear-delt machine that makes it easier to focus on opening through the upper back without shrugging or swinging.", "Set the seat and handles so the shoulders feel comfortable.", "Open the arms by squeezing through the rear delts.", "Control the return instead of letting the handles fly back."),
        ["Romanian Deadlift"] = Create("A hinge lift that builds the hamstrings and glutes by teaching you to push the hips back and stay long through the spine.", "Push the hips back while keeping the weight close.", "Keep a soft knee bend and a long neutral spine.", "Stand tall by driving the hips through."),
        ["Russian Twists"] = Create("A rotational core exercise that works best when the ribcage turns with control instead of the arms just swinging side to side.", "Rotate the ribs as one unit.", "Keep the chest tall instead of collapsing down.", "Move side to side with control."),
        ["Seated Cable Row"] = Create("A controlled horizontal pull that works best when you stay tall and bring the handle to you, instead of rocking the whole body back and forth.", "Sit tall before the rep starts.", "Pull the handle toward the lower ribs with the elbows driving back.", "Reach forward slowly so you do not lose posture."),
        ["Seated Calf Raise"] = Create("A seated calf exercise that emphasizes control through the ankle and a clean squeeze at the top instead of bouncing.", "Press through the ball of the foot.", "Pause briefly at the top.", "Lower slowly into a comfortable stretch."),
        ["Seated Dumbbell Shoulder Press"] = Create("A seated overhead press that lets you focus on shoulder strength while keeping the lower body out of the movement.", "Sit tall and keep the trunk braced.", "Press both dumbbells smoothly overhead.", "Lower evenly to a strong shoulder position."),
        ["Single-Arm Cable Triceps Extension"] = Create("A one-arm triceps movement that makes it easier to clean up side-to-side differences as long as the elbow stays steady.", "Keep the elbow stable and near the body line.", "Fully straighten the arm with control.", "Return slowly to the start."),
        ["Single-Leg Balance Hold"] = Create("A simple balance hold that trains the foot, ankle, and hip to work together while you stay calm and steady.", "Keep a soft bend in the stance knee.", "Hold the pelvis level.", "Use slow breathing and small balance corrections."),
        ["Sit-to-Stand"] = Create("A practical strength drill that builds confidence getting up from a chair by teaching you to use the legs instead of collapsing or rocking around.", "Plant the feet firmly before you stand.", "Lean slightly forward, then push through the whole foot.", "Finish tall and sit back down with control."),
        ["Skull Crushers"] = Create("A lying triceps exercise that works best when the upper arms stay mostly still and the elbows do the moving.", "Keep the upper arms steady instead of drifting.", "Lower the weight under control.", "Extend back up smoothly without bouncing."),
        ["Step-Up"] = Create("A one-leg strength and balance exercise where the front leg should do most of the work to lift you onto the platform.", "Plant the full lead foot on the step before you drive up.", "Push through the lead leg instead of springing off the trail foot.", "Stand tall at the top, then step down under control."),
        ["Standing Calf Raise"] = Create("A standing calf exercise that works best when you rise straight up and own the top position instead of bouncing through the reps.", "Keep pressure through the ball of the foot.", "Rise straight up without rolling the ankles in or out.", "Lower slowly so the calves stay under tension."),
        ["Stiff-Leg Deadlift"] = Create("A hamstring-heavy hinge variation where the reduced knee bend means you really need to move from the hips and stay long through the spine.", "Keep the legs long but not locked hard.", "Move from the hips, not the lower back.", "Raise the weight by driving the hips through."),
        ["Suitcase Carry"] = Create("A one-sided carry that builds grip and side-to-side trunk strength by asking you not to lean toward the load.", "Stand tall without leaning toward the weight.", "Walk with controlled even steps.", "Keep the ribs stacked over the hips."),
        ["Supported Split Squat"] = Create("A split squat with light support that helps you focus on leg strength and control without balance being the limiting factor.", "Use the support for balance, not to pull yourself up.", "Lower straight down with control.", "Drive through the front foot on the way up."),
        ["T-Bar Row"] = Create("A heavy row that lets you load the back hard, as long as you stay braced and do not turn it into a torso heave.", "Brace the torso before you pull.", "Row the handle toward the lower chest or upper stomach.", "Control the lowering phase instead of dropping it."),
        ["Tandem Stance Hold"] = Create("A narrow-stance balance drill that asks you to stay tall and steady when your base of support is limited.", "Keep your posture tall and eyes forward.", "Lightly brace the trunk.", "Hold steady without wobbling into the hips."),
        ["Trap Bar Deadlift"] = Create("A deadlift variation that often feels more balanced and upright, but still depends on a strong brace and a clean push through the floor.", "Brace before you start the pull.", "Push through the floor and stand tall inside the bar.", "Lower with control instead of dropping into the bottom."),
        ["Walking Lunge"] = Create("A traveling lunge that builds strength and coordination one step at a time, especially when each rep stays smooth and balanced.", "Take controlled steps instead of reaching too far.", "Lower evenly through both knees.", "Stay tall as you move into the next rep."),
        ["Wall Push-Up"] = Create("A beginner-friendly push-up that lets you practice solid pressing mechanics while keeping the movement approachable and controlled.", "Keep your body in one straight line from head to heel.", "Lower the chest toward the wall in one piece.", "Press away without letting the shoulders shrug up."),
        ["Weighted Pull-Up"] = Create("A loaded pull-up that keeps the same basic pattern as a regular pull-up, but asks for even more control and upper-back strength.", "Brace before you leave the dead hang.", "Pull the chest up without swinging.", "Return under control to a full hang.")
    };

    public static bool HasInfo(string? exerciseName)
        => TryGetInfo(exerciseName, out _);

    public static ExerciseInfo GetInfo(string? exerciseName)
        => TryGetInfo(exerciseName, out var info)
            ? info
            : Create(
                "A strength or movement exercise used in your workout plan.",
                "Move with control.",
                "Stay in a pain-free range.",
                "Focus on posture and alignment.");

    public static bool TryGetInfo(string? exerciseName, out ExerciseInfo info)
    {
        if (string.IsNullOrWhiteSpace(exerciseName))
        {
            info = default!;
            return false;
        }

        return ExactInfoMap.TryGetValue(exerciseName.Trim(), out info!);
    }

    private static ExerciseInfo Create(string summary, params string[] cues)
        => new(summary, cues);
}
